// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDc8vqw_2GkFHW_IB5TBJa3uH_chldu53Y',
    appId: '1:902363470595:web:1c2fd4a47b1203d40c6736',
    messagingSenderId: '902363470595',
    projectId: 'dywa-pratama',
    authDomain: 'dywa-pratama.firebaseapp.com',
    storageBucket: 'dywa-pratama.appspot.com',
    measurementId: 'G-F618X1VSX5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVjG33pTdqI8ftBME-l4ggPjwTcXWixqo',
    appId: '1:902363470595:android:2bda428c738533030c6736',
    messagingSenderId: '902363470595',
    projectId: 'dywa-pratama',
    storageBucket: 'dywa-pratama.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0_H35-PVZV8bYx-EsgXz3mclXHIaQXgI',
    appId: '1:902363470595:ios:1ae4c8ceeba2f0fc0c6736',
    messagingSenderId: '902363470595',
    projectId: 'dywa-pratama',
    storageBucket: 'dywa-pratama.appspot.com',
    iosBundleId: 'com.farmagitechs.personalia',
  );

}